### ISSUE TITLE
`Vec` missing features

### ISSUE THREAD

**Issue by leddoo** [leddoo/sti#5]
- [x] `vec!` and `vec_in!` macros.
  - [x] `Vec::from_value(value: T, len: usize) -> Vec<T> where T: Clone` and `from_value_in`. 
  - [x] `Vec::from_array<n>(values: [T; n]) -> Vec<T>` and `from_array_in`.
  - [x] use those and `new/_in` for the macros.
- [x] `Vec: From<I> where I: Iterator<Item=T>`
  - `std`'s vec uses `FromIterator`. that's probably for `collect::<Vec<_>>`. `Vec::from(some_iterator)` is nicer imo.
- [x] `Vec: PartialEq, Eq, Hash`.
- [x] `Vec: core::fmt::Write`

**Comment by rookieCookies** [comment]
#20

**Comment by leddoo** [comment]
looks like we're done here 👌
